CONFIG_FILENAME = "site.yaml"

DEFAULT_PLUGIN_DIR = "plugins"
DEFAULT_TEMPLATE_DIR = "templates"
DEFAULT_STATIC_DIR = "public"
DEFAULT_RESOURCE_DIR = "resources"

DEFAULT_API_URL = "/api"
DEFAULT_ADMIN_URL = "/admin"
DEFAULT_SITE_URL = "/"
DEFAULT_STATIC_URL = "/static"
