import ez


PLUGINS_DIRECTORY = ez.site.PLUGINS

PLUGINS_PUBLIC_API_DIRECTORY_NAME = "lib/public-api"
PLUGINS_PUBLIC_API_MODULE_NAME = "ez_plugins"

PLUGINS_PUBLIC_API_DIR = ez.SITE_DIR / PLUGINS_PUBLIC_API_DIRECTORY_NAME / PLUGINS_PUBLIC_API_MODULE_NAME

PLUGIN_MANIFEST_FILENAME = "manifest.yaml"
